# Generated by Django 4.1.3 on 2022-11-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratting',
            new_name='rating',
        ),
    ]
