from .last_added_Item_view_test import *
from .list_item_by_categories_view_test import *
from .create_item_view_test import *
from .add_item_to_order_view_test import *
from .delete_item_view_test import *
from .details_item_view_test import *
from .edit_Item_view_test import *
from .order_list_view_test import *
from .order_remove_test import *